/**:
  ros__parameters:
    NON_TELEOP: false
    MASTER_LOOP_RATE: 500
    VELOCITY_DIVISION: 0.033

    # Twist Max Values (Radyan)
    MAX_METERS_PER_SEC: 0.082
    MAX_RADIANS_PER_SEC: 0.30768  # 17.629 derece

    NUMBER_OF_HEAD_SEGMENTS: 0
    NUMBER_OF_LEGS: 6
    NUMBER_OF_LEG_SEGMENTS: 3

    # Initial Coxa Offsets (Radyan)
    # 60 deg -> 1.0472 rad
    INIT_COXA_ANGLE: [-1.0472, 0.0, 1.0472, -1.0472, 0.0, 1.0472]

    # Mesafeler (Metre)
    COXA_TO_CENTER_X: [-0.147, 0.0, 0.147, -0.147, 0.0, 0.147]
    COXA_TO_CENTER_Y: [0.08475, 0.170, 0.08475, 0.08475, 0.170, 0.08475]
    INIT_FOOT_POS_X: [-0.12124, 0.0, 0.12124, -0.12124, 0.0, 0.12124]
    INIT_FOOT_POS_Y: [0.07, 0.140, 0.07, 0.07, 0.140, 0.07]
    INIT_FOOT_POS_Z: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03]

    # Leg Measurements
    COXA_LENGTH: 0.052
    FEMUR_LENGTH: 0.065
    TIBIA_LENGTH: 0.133
    TARSUS_LENGTH: 0.00

    # Body FK maximum rotation (Radyan)
    BODY_MAX_ROLL: 0.174533   # 10 derece
    BODY_MAX_PITCH: 0.174533  # 10 derece
    BODY_MAX_YAW: 0.349066    # 20 derece
    STANDING_BODY_HEIGHT: 0.08

    # Head FK maximum rotation (Radyan)
    HEAD_MAX_YAW: 0.959931    # 55 derece
    HEAD_MAX_PITCH: 0.436332  # 25 derece

    # Body auto levelling parameters (Radyan)
    MAX_BODY_ROLL_COMP: 0.20944
    MAX_BODY_PITCH_COMP: 0.20944
    COMPENSATE_INCREMENT: 0.0001745
    COMPENSATE_TO_WITHIN: 0.0174533

    # Gait Settings
    CYCLE_LENGTH: 50
    LEG_LIFT_HEIGHT: 0.07
    MAX_LIFT_HEIGHT: 0.070
    GAIT_STYLE: "RIPPLE" # Razbot için Ripple yürüyüşü varsayılan
    INTERPOLATION_LOOP_RATE: 550

    # Servo Map (Açı ofsetleri Radyana çevrilmiştir)
    # Örn: 300 deg -> 5.2359 rad | 14 deg -> 0.2443 rad | -48 deg -> -0.8377 rad
    SERVOS:
      '01': {name: coxa_joint_RR, type: AX, id: 8, ticks: 1024, center: 512, max_radians: 5.2359, sign: -1, offset: 0.0}
      '02': {name: femur_joint_RR, type: AX, id: 10, ticks: 1024, center: 512, max_radians: 5.2359, sign: -1, offset: 0.2443}
      '03': {name: tibia_joint_RR, type: AX, id: 12, ticks: 1024, center: 512, max_radians: 5.2359, sign: -1, offset: -0.8377}
      '04': {name: coxa_joint_RM, type: AX, id: 14, ticks: 1024, center: 512, max_radians: 5.2359, sign: -1, offset: 0.0}
      '05': {name: femur_joint_RM, type: AX, id: 16, ticks: 1024, center: 512, max_radians: 5.2359, sign: -1, offset: 0.2443}
      '06': {name: tibia_joint_RM, type: AX, id: 18, ticks: 1024, center: 512, max_radians: 5.2359, sign: -1, offset: -0.8377}
      # ... (Diğer bacaklar RR/RM mantığıyla aynı radyan dönüşümleriyle devam etmeli)